[package]
name = "mypythonpackage"
version = "0.2.0"
edition = "2026"

[lib]
name = "_core"          # This becomes the Python extension name
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

